### ISSUE TITLE
ACAP implementation

### ISSUE THREAD

**Issue by MaxMayya** [Juyong/DHNN_BodyRepresentation#1]
Thank you for sharing this very interesting labor. I want to test your model on a specific dataset but I cannot find the implementation of ACAP anywhere. Could you please point me to some code?

Many thanks

**Comment by jby1993** [comment]
Hello, Our ACAP implementation is not available now.  If we prepare to release the code, I will notify you. By the way, you can  check the original author(http://geometrylearning.com/lin/) website to see whether they share the code.

**Comment by MaxMayya** [comment]
Thanks for the quick reply. I found Windows binaries [here](https://github.com/gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer/blob/master/matlabscript/ACAPOpt.exe) and [here](https://github.com/aldehydecho/convMesh/tree/master/genfeature) (hope this helps Win users) but no Linux one unfortunately!
Yes I'll be very grateful if you share your implementation of ACAP once you have it.

**Comment by MaxMayya** [comment]
**Update**
ACAP authors have finally published there linux implementation [here](https://github.com/gaolinorange/Automatic-Unpaired-Shape-Deformation-Transfer/tree/master/ACAP_linux).
I want to test that on the dataset you share; for ex. I want to reproduce `dataset/neutral_fs/SPRING2647.txt` from `dataset/neutral_ms/SPRING2647.obj` and the reference mesh. Could you please point me to the reference mesh used to generate the ACAP features please?

**Comment by jby1993** [comment]
Actually, the reference mesh is not in the dataset. The reference mesh 'template.obj' can be found in the downloaded trained model(See Install). For some reason, we choose this non-neutral shape mesh as reference mesh, this is not very suitable. You can choose another neutral mesh as reference mesh and recompute your acap feature. And another note, different mixed integer optimization setting can lead to different acap values, even with same ref mesh. So, you may get different acap feature with their code.

**Comment by MaxMayya** [comment]
Yes different optimizers could end up with different results I already noticed such behaviour on their test vectors. Out of curiosity, what optimizer do you use? Gurobi?

**Comment by jby1993** [comment]
Yes. We also use gurobi.
