### ISSUE TITLE
How much memory of GPU is required to run this program?

### ISSUE THREAD

**Issue by ghost** [Juyong/DHNN_BodyRepresentation#3]
This is a great research.I learn some knowledge from your paper and program.Thanks vary much. Excuse me, when I run  a  code of the DFaust registration experiment after installing the batch_knn library, unfortunately，there is a complier error which to say "THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THC/
THCCachingHostAllocator.cpp line=278 error=700 : an illegal memory access was encountered".
I found some solutions about this error,it is unsuccessful. Is this error related to out of memory ?So I want to know memory of GPU which required to run this program at least?

**Comment by jby1993** [comment]
If this is caused by batch_knn, it should be out of gpu memory. Maybe you can change batch_size to a smaller value to see whether it works.
