### ISSUE TITLE
Torch dependencies

### ISSUE THREAD

**Issue by MaxMayya** [Juyong/DHNN_BodyRepresentation#4]
Hi,
What version are you using for `torch-sparse`, `torch-scatter`, `torch-cluster` and `torch-spline-conv`?

**Comment by jby1993** [comment]
These libs are used by PyTorch geometric, My used version is 1.3.2. You can find its dependence on the website of pytorch geometric. And I list my used version here as reference: torch-sparse(0.4.0), torch-scatter(1.3.1), torch-cluster(1.4.4), torch-spline-conv(1.1.0).

**Comment by MaxMayya** [comment]
Thank you the versions you provided worked like a charm!
